import "~/styles/globals.css";

import { type Metadata } from "next";
import { HydrateClient } from "~/trpc/server";
import { TRPCReactProvider } from "~/trpc/react";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { cn } from "~/lib/utils";
import { FontProvider } from "~/lib/context/font-context";
import schroddy from "../assets/images/schroddy.svg";
import { AnimatedSchroddy } from "~/components/layout/animated-schroddy";

// Font files can be colocated inside of `pages`
const cartoonTown = localFont({
  src: "../assets/fonts/cartoon-town.ttf",
  variable: "--font-cartoon-town",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <FontProvider>
      <html
        lang="en"
        className={cn(
          inter.variable,
          cartoonTown.variable,
          "font-sans transition-all duration-300", // Added transition for smooth font change
        )}
      >
        <body>
          <AnimatedSchroddy src={schroddy} />
          <TRPCReactProvider>
            <HydrateClient>{children}</HydrateClient>
          </TRPCReactProvider>
        </body>
      </html>
    </FontProvider>
  );
}
