import "~/styles/globals.css";

import { type Metadata } from "next";
import { HydrateClient } from "~/trpc/server";
import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "~/components/layout/header";
import { Footer } from "~/components/layout/footer";
import localFont from "next/font/local";
import { Comic_Neue } from "next/font/google";
import { cn } from "~/lib/utils";

// Font files can be colocated inside of `pages`
const cartoonTown = localFont({
  src: "./assets/fonts/cartoon-town.ttf",
  variable: "--font-cartoon-town",
});

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-comic-neue",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        comicNeue.variable,
        cartoonTown.variable,
        "font-sans", // Comic Neue as default font
      )}
    >
      <body>
        <TRPCReactProvider>
          <HydrateClient>
            <div className="flex min-h-screen flex-col">
              <Header />
              <main className="flex-1">
                <div className="mx-auto w-full max-w-7xl">{children}</div>
              </main>
              <Footer />
            </div>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
