import "~/styles/globals.css";

import { type Metadata } from "next";
import { HydrateClient } from "~/trpc/server";
import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "~/components/layout/header";
import { Footer } from "~/components/layout/footer";
import localFont from "next/font/local";
import { Acme } from "next/font/google";
import { cn } from "~/lib/utils";
import { FontProvider } from "~/lib/context/font-context";
import schroddy from "../assets/images/schroddy.svg";
import Image from "next/image";
import { AnimatedSchroddy } from "~/components/layout/animated-schroddy";

// Font files can be colocated inside of `pages`
const cartoonTown = localFont({
  src: "../assets/fonts/cartoon-town.ttf",
  variable: "--font-cartoon-town",
});

const acme = Acme({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-acme",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <FontProvider>
      <html
        lang="en"
        className={cn(
          acme.variable,
          cartoonTown.variable,
          "font-sans transition-all duration-300", // Added transition for smooth font change
        )}
      >
        <body>
          <AnimatedSchroddy src={schroddy} />
          <TRPCReactProvider>
            <HydrateClient>
              <div className="flex min-h-screen flex-col">
                <Header />
                <main className="flex-1">
                  <div className="mx-auto w-full max-w-7xl">{children}</div>
                </main>
                <Footer />
              </div>
            </HydrateClient>
          </TRPCReactProvider>
        </body>
      </html>
    </FontProvider>
  );
}
