name: autofix.ci
on:
  pull_request:
  push:
    branches: [ ${{ github.event.repository.default_branch }} ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx prettier --write . --ignore-path .prettierignore

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: "chore(autofix): apply formatting"
